### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/jasonism#15]
Add a license to the github repo

**Comment by JBYT27** [comment]
Wait, isn't this easy though? Sorry if thats rude.

**Comment by VulcanWM** [comment]
Yeah but I usually forget stuff lmao so that’s why I added this here

**Comment by VulcanWM** [comment]
Also what license do you recommend for this  project? Noting the fact I might add features to get money from this later

**Comment by JBYT27** [comment]
Oh, lol, okay.

Wait, so you kinda want to like make money irl from this project? If so, I would probably recommend `MIT` License, or probably `Apache` License.
> Reasons for them are because of copyright conditions, no trademark use, and commercial use is allowed.

However, you *could* take a look at license [here](https://choosealicense.com/).

**Comment by JBYT27** [comment]
Hope this helps!

**Comment by VulcanWM** [comment]
Thanks for your help! I’ll check these out

**Comment by VulcanWM** [comment]
Added the `Apache` License! Thanks again!

**Comment by JBYT27** [comment]
No problem! Glad I could help :)
