### ISSUE TITLE
.gitignore not working

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/jasonism#18]

**Comment by VulcanWM** [comment]
@JBYT27
Sorry for bothering you
I’ve seen you use .gitignore before so maybe you can help?

**Comment by JBYT27** [comment]
No problem, feel free to ping me whenever :)

Okay, so one thing I should mention is that the `.gitignore` won't hide the files or folders, it just ignores them. And to fix that, you need to add a slash at the beginning of every directory. So the "fixed" `.gitignore` could look like this:

```shell
/__pycache__
pyproject.toml
poetry.lock
```

Hope this helps!

**Comment by VulcanWM** [comment]
oh okay, so ill have to physically deleted the files from the github repo first and then when the code above is that, it won't show it when pushing?

**Comment by JBYT27** [comment]
Well, the files *will* show, you can't really prevent that, but you can make the program *ignore* the files you enter in the `.gitignore`. You can delete them, but they will probably show up again once you run the program on Replit or any other code editor. The only thing you can do is either add some code in Python that constantly deletes the directories you want deleted, or leave it and add the `.gitignore` to make the program ignore the following directories. A code example can be viewed [here](https://www.w3schools.com/python/python_file_remove.asp)

Hope this helps!

**Comment by VulcanWM** [comment]
thanks ill try it out!

**Comment by JBYT27** [comment]
No problem, hope it works!

**Comment by VulcanWM** [comment]
deleting the files which I included in `.gitignore` caused a completely new error in pymongo which I’ve never seen before lmao
I think I’ll just stick to just not having a .gitignore file

**Comment by JBYT27** [comment]
Lmao oof. Okay!

**Comment by VulcanWM** [comment]
Thanks for your time anyway!

**Comment by JBYT27** [comment]
No problem, ping me anytime if you need help! :D

**Comment by VulcanWM** [comment]
lmao you’ll be getting lots of pings from now on
also can I ask what time zone ur in?

**Comment by JBYT27** [comment]
Haha, dw, its 100% fine ;)
Uh, EST (im in U.S lol)

**Comment by VulcanWM** [comment]
oh dyu still have online school?

**Comment by JBYT27** [comment]
Well, there's still an option for it, but I'm in in-school now
