### ISSUE TITLE
[DOCUMENT] Add Code of Conduct

### ISSUE THREAD

**Issue by JBYT27** [VulcanWM/jasonism#19]
Heya, so this seems community based, but if you don't want to do the following, you don't have to.

So because this seems community based, I think adding a Code of Conduct may be a good addition to the document and to this project.

However, this is your choice, and this is just my opinion and how I see things lol :)

**Comment by VulcanWM** [comment]
oh yeah good idea
thanks I'll do it later!

**Comment by JBYT27** [comment]
No problem! :D

**Comment by VulcanWM** [comment]
did this! thanks for the idea :)
